#global_cflags = ARGUMENTS.get('CFLAGS', '-Wall -Wextra -O2 -fomit-frame-pointer')
#global_cxxflags = ARGUMENTS.get('CXXFLAGS', global_cflags + ' -fno-exceptions -fno-rtti')
#global_defines = ' -DHAVE_STDINT_H'
#vars = Variables()
#vars.Add('CC')
#vars.Add('CXX')
#
#env = Environment(CPPPATH = ['src', 'include', '../common'],
#                  CFLAGS = global_cflags + global_defines,
#                  CXXFLAGS = global_cxxflags + global_defines,
#                  variables = vars)

import os
env = Environment(ENV = os.environ)

env['AR']      = 'arm-wiz-linux-gnu-ar'
env['AS']      = 'arm-wiz-linux-gnu-as'
env['CC']      = 'arm-wiz-linux-gnu-gcc'
env['CXX']     = 'arm-wiz-linux-gnu-g++'
env['LD']      = 'arm-wiz-linux-gnu-ld'
#env['LINK']    = 'arm-wiz-linux-gnu-g++'
env['LINK']    = 'arm-wiz-linux-gnu-ld'
env['OBJCOPY'] = 'arm-wiz-linux-gnu-objcopy'
env['RANLIB']  = 'arm-wiz-linux-gnu-ranlib'
env['STRIP']   = 'arm-wiz-linux-gnu-strip'

env['CCFLAGS']    = ['-Wall', '-Wextra', '-O2', '-fomit-frame-pointer']
env['CXXFLAGS']   = ['-fno-exceptions', '-fno-rtti']
env['CPPDEFINES'] = ['-DHAVE_STDINT_H']
env['CPPPATH']    = ['#src', '#include', '#../common', '/opt/hmnwiz/include']

sourceFiles = Split('''
			src/bitmap_font.cpp
			src/cpu.cpp
			src/gambatte.cpp
			src/initstate.cpp
			src/interrupter.cpp
			src/interruptrequester.cpp
			src/loadres.cpp
			src/memory.cpp
			src/sound.cpp
			src/state_osd_elements.cpp
			src/statesaver.cpp
			src/tima.cpp
			src/video.cpp
			src/mem/cartridge.cpp
			src/mem/memptrs.cpp
			src/mem/pakinfo.cpp
			src/mem/rtc.cpp
			src/sound/channel1.cpp
			src/sound/channel2.cpp
			src/sound/channel3.cpp
			src/sound/channel4.cpp
			src/sound/duty_unit.cpp
			src/sound/envelope_unit.cpp
			src/sound/length_counter.cpp
			src/video/ly_counter.cpp
			src/video/lyc_irq.cpp
			src/video/next_m0_time.cpp
			src/video/ppu.cpp
			src/video/sprite_mapper.cpp
		   ''')

conf = env.Configure()

if conf.CheckHeader('zlib.h'):
	sourceFiles.append('src/file/unzip/unzip.c')
	sourceFiles.append('src/file/unzip/ioapi.c')
	sourceFiles.append('src/file/file_zip.cpp')
else:
	sourceFiles.append('src/file/file.cpp')

conf.Finish()

env.Library('gambatte', sourceFiles)
